// server.rs — Leptos server function for contact form submission.

use leptos::prelude::*;
use leptos::server_fn::error::ServerFnError;

#[cfg(feature = "ssr")]
use crate::{delivery::ContactDeliveryContext, error::ContactValidationError, model::ContactInput};

/// Submit a contact form enquiry.
///
/// Leptos server function compiled to `POST /api/submit_contact`.
///
/// # Arguments
///
/// | Argument     | Required | Notes |
/// |--------------|----------|-------|
/// | `name`       | Yes | Enquirer display name |
/// | `email`      | Yes | Used as `Reply-To`; never as `From` |
/// | `subject`    | No  | Optional subject line |
/// | `message`    | Yes | Plain-text body, up to [`MESSAGE_MAX_LEN`](crate::model::MESSAGE_MAX_LEN) characters |
/// | `website`    | —   | Honeypot; must be empty |
/// | `csrf_token` | —   | `Option<String>`; verified when `CsrfConfigContext` is in context |
///
/// # CSRF verification
///
/// When the `csrf` feature is enabled **and** [`CsrfConfigContext`](crate::csrf::CsrfConfigContext)
/// is present in the Leptos context, the `csrf_token` field is verified with
/// [`verify_csrf_token`](crate::csrf::verify_csrf_token).
///
/// When the `csrf` feature is enabled but `CsrfConfigContext` is **not** provided,
/// the call is **rejected** with a configuration error.  This fail-closed behaviour
/// prevents silent CSRF bypass when the context injection is accidentally omitted.
///
/// # Server-side policy
///
/// When [`ContactServerPolicy`](crate::config::ContactServerPolicy) is provided via
/// context, `require_subject` and `max_message_len` are enforced server-side.
///
/// # Success redirect
///
/// When [`ContactSuccessRedirect`](crate::config::ContactSuccessRedirect) is
/// provided via context, a successful delivery runs it before returning, so
/// the visitor is sent to the configured page with or without JavaScript.
/// Without it, behaviour is unchanged: a JavaScript client shows the inline
/// success message and a no-JavaScript client reloads the form page.
///
/// # Security
///
/// - Server-side validation is always performed.
/// - A non-empty `website` silently succeeds (honeypot).
/// - Delivery errors are logged server-side; only a generic string reaches the client.
/// - SMTP credentials never leave the server.
#[server(endpoint = "submit_contact")]
pub async fn submit_contact(
    name: String,
    email: String,
    subject: Option<String>,
    message: String,
    website: String,
    /// CSRF token generated by `ContactForm`.  `Option<String>` so that forms
    /// lacking the hidden field (e.g. upgraded deployments) do not fail at
    /// deserialization.  When the `csrf` feature is active and
    /// `CsrfConfigContext` is provided, a missing token is treated as invalid.
    csrf_token: Option<String>,
) -> Result<(), ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        use leptos::context::use_context;

        // 1. CSRF verification — fail-closed when `csrf` feature is enabled.
        #[cfg(feature = "csrf")]
        {
            use crate::csrf::{CsrfConfigContext, verify_csrf_token};
            let Some(csrf_config) = use_context::<CsrfConfigContext>() else {
                tracing::error!(
                    "csrf feature is enabled but CsrfConfigContext is not provided \
                     — check that you supply it in both handler closures"
                );
                return Err(ServerFnError::ServerError(
                    "Contact form security is not configured. \
                     Please contact the site administrator."
                        .into(),
                ));
            };
            let token = csrf_token.as_deref().unwrap_or("");
            if !verify_csrf_token(token, &csrf_config) {
                tracing::warn!("CSRF token verification failed");
                return Err(ServerFnError::Args(
                    "Invalid or expired security token. Please reload the page.".into(),
                ));
            }
        }
        // Without `csrf` the parameter is still part of the wire contract but
        // nothing reads it; bind it so the combination compiles warning-free.
        #[cfg(not(feature = "csrf"))]
        let _ = &csrf_token;

        // 2. Normalise raw input.
        let input = ContactInput::from_raw(name, email, subject, message, website);

        // 3. Honeypot — silent success.
        match input.check_honeypot() {
            Ok(()) => {}
            Err(ContactValidationError::HoneypotTriggered) => return Ok(()),
            Err(e) => {
                tracing::error!(error = %e, "unexpected honeypot error");
                return Err(ServerFnError::ServerError(
                    "An unexpected error occurred.".into(),
                ));
            }
        }

        // 4. Server-side field validation.
        let field_errors = input.validate_fields();
        if !field_errors.is_empty() {
            tracing::debug!(
                name_err = field_errors.name.is_some(),
                email_err = field_errors.email.is_some(),
                subject_err = field_errors.subject.is_some(),
                message_err = field_errors.message.is_some(),
                "contact form validation failed"
            );
            return Err(ServerFnError::Args(field_errors.into_server_fn_message()));
        }

        // 5. Server-side policy (require_subject, max_message_len).
        {
            use crate::config::ContactServerPolicy;
            if let Some(policy) = use_context::<ContactServerPolicy>() {
                let errs = policy.check(&input);
                if !errs.is_empty() {
                    return Err(ServerFnError::Args(errs.into_server_fn_message()));
                }
            }
        }

        // 6. Delivery backend.
        let Some(delivery) = use_context::<ContactDeliveryContext>() else {
            tracing::error!("ContactDeliveryContext not provided — check server setup");
            return Err(ServerFnError::ServerError(
                "Contact form is not configured. Please contact the site administrator.".into(),
            ));
        };

        // 7. Read the optional success redirect *before* awaiting delivery:
        // Leptos context is not reachable after an await point here.
        let success_redirect = use_context::<crate::config::ContactSuccessRedirect>();

        // 8. Deliver.
        if let Err(e) = delivery.deliver(input).await {
            tracing::error!(error = %e, "contact form delivery failed");
            return Err(ServerFnError::ServerError(
                "Failed to send message. Please try again later.".into(),
            ));
        }

        // 9. Success redirect, so the no-JS path can confirm too.
        if let Some(redirect) = success_redirect {
            redirect.apply();
        }

        return Ok(());
    }

    #[allow(unreachable_code)]
    Err(ServerFnError::ServerError("SSR not enabled".into()))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(all(test, feature = "ssr"))]
mod tests;
