// server.rs — Leptos server function for contact form submission.

use leptos::prelude::*;
use leptos::server_fn::error::ServerFnError;

#[cfg(feature = "ssr")]
use crate::{
    delivery::ContactDeliveryContext,
    error::ContactValidationError,
    model::ContactInput,
};

/// Submit a contact form enquiry.
///
/// This is a Leptos **server function** (`POST /api/submit_contact`).
/// Treat it like any other public API endpoint.
///
/// # Arguments
///
/// | Argument     | Required | Notes                               |
/// |--------------|----------|-------------------------------------|
/// | `name`       | Yes      | Enquirer display name               |
/// | `email`      | Yes      | Used as `Reply-To`; never as `From` |
/// | `subject`    | No       | Optional subject line               |
/// | `message`    | Yes      | Plain-text body, up to 4 000 chars  |
/// | `website`    | —        | Honeypot; must be empty             |
/// | `csrf_token` | —        | Verified when `CsrfConfigContext` is in context |
///
/// # CSRF verification
///
/// When [`CsrfConfigContext`](crate::csrf::CsrfConfigContext) is present in
/// the Leptos context, the `csrf_token` argument is verified with
/// [`verify_csrf_token`](crate::csrf::verify_csrf_token).  A missing or
/// invalid token results in a `ServerFnError::Args` with a generic message.
///
/// When `CsrfConfigContext` is absent, `csrf_token` is ignored and
/// verification is skipped.  This maintains backward compatibility.
///
/// # Security
///
/// - Server-side validation is **always** performed.
/// - A non-empty `website` silently succeeds (honeypot).
/// - Delivery errors are logged server-side only.
/// - SMTP credentials never leave the server.
#[server]
pub async fn submit_contact(
    name: String,
    email: String,
    subject: Option<String>,
    message: String,
    website: String,
    /// CSRF token generated by [`generate_csrf_token`](crate::csrf::generate_csrf_token)
    /// and embedded by `ContactForm`.  Verified when `CsrfConfigContext` is in context.
    csrf_token: String,
) -> Result<(), ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        use leptos::context::use_context;

        // 1. CSRF verification (optional — skipped when CsrfConfigContext absent).
        #[cfg(feature = "csrf")]
        {
            use crate::csrf::{CsrfConfigContext, verify_csrf_token};
            if let Some(csrf_config) = use_context::<CsrfConfigContext>() {
                if !verify_csrf_token(&csrf_token, &csrf_config) {
                    tracing::warn!("CSRF token verification failed");
                    return Err(ServerFnError::Args(
                        "Invalid or expired security token. Please reload the page.".into(),
                    ));
                }
            }
        }

        // 2. Normalise raw input.
        let input = ContactInput::from_raw(name, email, subject, message, website);

        // 3. Honeypot — silent success.
        match input.check_honeypot() {
            Ok(()) => {}
            Err(ContactValidationError::HoneypotTriggered) => return Ok(()),
            Err(e) => {
                tracing::error!(error = %e, "unexpected honeypot error");
                return Err(ServerFnError::ServerError(
                    "An unexpected error occurred.".into(),
                ));
            }
        }

        // 4. Server-side validation — return per-field errors.
        let field_errors = input.validate_fields();
        if !field_errors.is_empty() {
            tracing::debug!(
                name_err    = field_errors.name.is_some(),
                email_err   = field_errors.email.is_some(),
                subject_err = field_errors.subject.is_some(),
                message_err = field_errors.message.is_some(),
                "contact form validation failed"
            );
            return Err(ServerFnError::Args(
                field_errors.into_server_fn_message(),
            ));
        }

        // 5. Delivery backend.
        let Some(delivery) = use_context::<ContactDeliveryContext>() else {
            tracing::error!("ContactDeliveryContext not provided — check server setup");
            return Err(ServerFnError::ServerError(
                "Contact form is not configured. Please contact the site administrator.".into(),
            ));
        };

        // 6. Deliver.
        if let Err(e) = delivery.deliver(input).await {
            tracing::error!(error = %e, "contact form delivery failed");
            return Err(ServerFnError::ServerError(
                "Failed to send message. Please try again later.".into(),
            ));
        }

        return Ok(());
    }

    #[allow(unreachable_code)]
    Err(ServerFnError::ServerError("SSR not enabled".into()))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(all(test, feature = "ssr"))]
mod tests;
